### ISSUE TITLE
[Question] - usable for sync scenarios?

### ISSUE THREAD

**Issue by gentledepp** [buvinghausen/SequentialGuid#4]
Hello!
I was wondering if the guids produced are usable for sync sceanrios.
For example:

we do have hundreds of Xamarin apps that create data with GUID primary key.
They sync their data and insert it to a central MSSQL Database. (Which should use the ID as clustered index)

Would you recommend such a scenario with your SequentialGuid implementation? 😍

**Comment by buvinghausen** [comment]
@gentledepp Yes the intent of this library is to be able to generate the keys on the frontier device and not have to go to the database to get them.  Since you are using MSSQL make sure you get the [SequentialSqlGuidGenerator](../blob/master/src/SequentialGuid/SequentialSqlGuidGenerator.cs#L10) which will generate the GUIDs so that they will sort properly in your clustered index.  You can see more about the subject from [Alberto Ferrari's blog post 14 years ago which ultimately inspired me to write this library](https://www.sqlbi.com/blog/alberto/2007/08/31/how-are-guids-sorted-by-sql-server/)

The byte order mapping happens [here](../blob/master/src/SequentialGuid/SequentialGuidExtensions.cs#L29)

You can also see more clearly from the test cases the differences [here](../blob/master/test/SequentialGuid.Tests/SequentialGuidTests.cs#L44)

It uses the [MongoDB Object Id spec](https://docs.mongodb.com/manual/reference/method/ObjectId/) the 5 byte random value they talk about is the first 3 bytes of the MD5 hash of the machine name and the low order 2 bytes of the process id.  The only other difference is rather than using the Unix timestamp I use the system time in ticks to get the 8 byte timestamp to fill out the remaining 4 bytes that a GUID needs as opposed to the original 12 byte object ID.

Let me know if you have any other questions.

**Comment by gentledepp** [comment]
This is awesome! Thank you for clarifying.
I am just wondering about two things:
1) We are using Xamarin and sqlite. How exactly can you get the machine name on from a mobile device using Xamarin? Has this been used by someone successfully already?
2) We are currently using an old approach: Having a normal PK uniqueidentifier in combination with a datetime as clusterid. This has its obvious drawbacks of not being able to directly locate the row on disk using the PK.
However, we would have to *migrate* from this system to using sequential guids.

Question: How risky is it to migrate from a `Id = Guid.NewGuid()` system to using `SequentialSqlGuidGenerator´? (Concerning ID clashes)

**Comment by buvinghausen** [comment]
@gentledepp I have not run it on Xamarin but I'm just using the Environment.MachineName currently.  That likely does not work so I'm totally open to doing some conditional compilation and making a Xamarin specific release that uses the [Xamarin.Essentials.DeviceInfo.Name](https://docs.microsoft.com/en-us/xamarin/essentials/device-information) property for that target framework moniker.

As far as collisions go there should be none as Guid.NewGuid() uses v4 of the specification so the digit above position 1 is always 4 and the digit above position 2 is always one of 8, 9, a, or b

```
18acac20-991e-437e-9529-a441452f6b7e
d6d68639-64c2-452e-95b7-16cf6dbf5301
b0943b6d-4779-4771-92bf-cc2d634fb671
218b5620-d30d-46d9-9c88-38a4ac64266e
de03042c-792f-4689-80ca-26287ceb2129
1175bb5d-d35e-4a46-aaac-0825c749dc3a
42864583-c0f6-4e44-8710-39c9a9146d43
223ca924-4b77-4931-bb94-c1d371894683
2c4495ab-19e4-4aeb-b647-10db8625791c
f5894345-cbe3-4fc7-92c3-d6d863f70411
              ^    ^
              1    2
```

With this library you get Guids that look like this with the normal sequential guid on the left and the SQL sorted rendition on the right.  From position 1 is the time stamp, position 2 is the machine name hash, position 3 is the process id, & position 4 is the sequence that is randomly seeded.

```
08d9319f-7e88-60e9-c5ff-1b1d20006fbc	bc6f0020-1d1b-ffc5-60e9-08d9319f7e88
08d9319f-7e8c-b796-c5ff-1b1d20006fbd	bd6f0020-1d1b-ffc5-b796-08d9319f7e8c
08d9319f-7e8d-1ed9-c5ff-1b1d20006fbe	be6f0020-1d1b-ffc5-1ed9-08d9319f7e8d
08d9319f-7e8d-350d-c5ff-1b1d20006fbf	bf6f0020-1d1b-ffc5-350d-08d9319f7e8d
08d9319f-7e8d-792d-c5ff-1b1d20006fc0	c06f0020-1d1b-ffc5-792d-08d9319f7e8d
08d9319f-7e8d-a86e-c5ff-1b1d20006fc1	c16f0020-1d1b-ffc5-a86e-08d9319f7e8d
08d9319f-7e8d-ce91-c5ff-1b1d20006fc2	c26f0020-1d1b-ffc5-ce91-08d9319f7e8d
08d9319f-7e8d-ea57-c5ff-1b1d20006fc3	c36f0020-1d1b-ffc5-ea57-08d9319f7e8d
08d9319f-7e8e-156d-c5ff-1b1d20006fc4	c46f0020-1d1b-ffc5-156d-08d9319f7e8e
08d9319f-7e8e-26a4-c5ff-1b1d20006fc5	c56f0020-1d1b-ffc5-26a4-08d9319f7e8e
^                  ^      ^   ^
1                  2      3   4
```

So if you go back to the Guid.NewGuid() positions in the SQL rendering position 1 comes from the machine hash 2nd byte which could be 4 in some instances but you have a 1/16th chance there and position 2 comes from the timestamp which will yield values from 8, 9, a, & b but with a 1/4 chance.  Of course mathematically you have about a 1 in 2^128 chance but it's infinitesimally small.

**Comment by gentledepp** [comment]
Thank you for the in-depth response!

Please do not depend on Xamarin.Essentials. I have used Xamarin libraries for 7 years now and I do not trust a single line of code they write.... :-(

I guess it would be easier for you to create some static property that returns the machinename and that can be overwritten. (e.g. just once. If it is not null, it will throw)

What we do to identify a device currently is that we simply store a guid in the application folder in some text file.
So as long as the app is not uninstalled, the identity remains the same.

This is the simplest solution and it proved to be the most stable and trustworthy one.

Could you think of enabling something like this?

**Comment by buvinghausen** [comment]
The machine name is not particularly important in the greater scheme of things so  could fill those bites with random values.  The important thing to figure out is what is the result of Environment.MachineName is so I can detect that and generate the random values as a fallback.

**Comment by gentledepp** [comment]
But isn't it important for the "sequentiality of things" that the machinename remains the same?
(Sorry for asking such potentially stupid questions)

**Comment by buvinghausen** [comment]
@gentledepp the only ironclad guarantee we can give on sorting is for Guids generated by the same machine.  The first component in the sort is the timestamp which of course means you get fidelity down to the tick (100 ms) even across machines but within that tick you could presumably have two devices generate an id and that would then not be guaranteed to sort due to the randomness of the values for the machine name, process id, and counter's initial seed value.

The other clustered index issue is the timing and frequency the devices will sync up with the servers to persist the information to your MSSQL database. What this does is limit your clustered index fragmentation issues to the best of our abilities in a distributed environment where you can still generate keys on devices that are completely offline and have them sync up once they do come online.

**Comment by buvinghausen** [comment]
@gentledepp I'm closing this for now due to inactivity.  If you need anything else please let me know.

**Comment by gentledepp** [comment]
All good! Questions answered ;-)
