### ISSUE TITLE
The MongoDB ObjectId specification is not correctly implemented.

### ISSUE THREAD

**Issue by teo-tsirpanis** [buvinghausen/SequentialGuid#6]
[According to MongoDB documentation](https://docs.mongodb.com/manual/reference/method/ObjectId/#mongodb-method-ObjectId), the timestamp part represents the seconds since the Unix epoch, but in https://github.com/buvinghausen/SequentialGuid/blob/5711949fa29b75f4c86724a22a7b06fb1d848a8c/src/SequentialGuid/SequentialGuidGeneratorBase.cs#L77-L95 the library uses the ticks since January 1 0001.

**Comment by buvinghausen** [comment]
@teo-tsirpanis you are indeed correct their ObjectId specification has 12 bytes of data in it where a Guid has 16 bytes of data in it.

So rather than create my own filler to fill the additional 4 bytes of data I just used the system ticks which provides a 64 bit integer for the timestamp rather than the Unix epoch which is a 32 bit integer (that will overflow on 1/19/2038)

The basis of the timestamp is not at all important IMHO the important things are

A) that the timestamp is encoded in the GUID
 
B) that the IDs sort sequentially in a clustered index in a database both of which this library accomplishes
